AsopaabiOnline.UI/Controllers/DireccionesParaPedidosController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using AsopaabiOnline.LogicaDeNegocio;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.AspNetCore.Identity;
using AsopaabiOnline.UI.Models;
using AsopaabiOnline.UI.Models.Enums;

namespace AsopaabiOnline.UI.Controllers
{//controlador de direcciones para pedidos
    public class DireccionesParaPedidosController : BaseController //hereda el controlador base para la notificacion de mensajes.

    {
        private readonly UserManager<User> userManager; //instancia de la clase  usuario para que sirva como administrador
        public DireccionesParaPedidosController(UserManager<User> userManager)//constructor del controlador direcciones para pedidos 
        {
            this.userManager = userManager;

        }

         //Método GET y POST para agregar direcciones

        [HttpGet]
    
        public IActionResult Agregar()
        {

            Modelo.DireccionPedido laDireccionDelPedido = new Modelo.DireccionPedido();

            CoordinadorDeProvincias elCoordinadorDeProvincias = new CoordinadorDeProvincias(); 


            laDireccionDelPedido.LaListaDeProvincias = elCoordinadorDeProvincias.ListarProvincias();//el coordinador obtiene la lista de provincias 


            return View(laDireccionDelPedido); //se muestran las provincias en la vista
        }

        [HttpPost]
       
        public async Task<IActionResult> Agregar(Modelo.DireccionPedido laDireccion)
        {
            try
            {
                if (laDireccion != null)
                {
                    var user = await userManager.GetUserAsync(HttpContext.User); //el administrador de usuarios obtiene el usuario del inicio de sesion
                    CoordinadorDeDireccionesParaPedidos elCoordinador = new CoordinadorDeDireccionesParaPedidos(); //se crea una instancia del coordinador de direcciones para pedidos
                    laDireccion.IdCliente = user.Id;  //se asigna el id del cliente a la direccion 
                    elCoordinador.Agregar(laDireccion); //el coordinador agrega la nueva direccion 

                    Alert("Dirección guardada.", NotificationType.success); //se muestra un mensaje de exito
                   


                }
                else //si no se agrega 
                {
                    Alert("Complete todos los campos.", NotificationType.info); // se  muestra un mensaje de informacion  
                    return View();
                }


                return RedirectToAction("Mostrar");



            }
            catch //si ocurre un error
            {


                Alert("Complete todos los campos.", NotificationType.error); // se muestra un mensaje de error
                return View();
            }
           

        }

     

        //Método para cargar los cantones en el select de la vista
        public JsonResult CargarCantones(int id)
        {
            CoordinadorDeCantones elCoordinador = new CoordinadorDeCantones();
            var losCantones = elCoordinador.ListarCantonesPorIdDeProvincia(id); //el coordinador brinda la lista de cantones por id de provincia 
            return Json(new SelectList(losCantones, "Id", "Nombre")); //se listan en un select
        }


        //Método para cargar los distritos en el select de la vista
        public JsonResult CargarDistritos(int id)
        {
            CoordinadorDeDistritos elCoordinador = new CoordinadorDeDistritos();
            var losDistritos = elCoordinador.ListarDistritosPorIdDeCanton(id);//el coordinador brinda la lista de los distritos por id de canton 
            return Json(new SelectList(losDistritos, "Id", "Nombre"));//se listan en un select
        }


        //Método para mostrar la lista de direcciones
        [HttpGet]
        [Route("DireccionesParaPedidos/Mostrar")]
        public async Task<IActionResult> Mostrar()
        {

            CoordinadorDeDireccionesParaPedidos elCoordinador = new CoordinadorDeDireccionesParaPedidos();
            var user = await userManager.GetUserAsync(HttpContext.User); //el administrador de usuario trae el usuario logueado


            return  View(elCoordinador.ListarDirecciones(user.Id)); //el coordinador devuelve a la vista la lista de direcciones por id de usuario
        }


        //Método GET y POST para eliminar una direccion por id

        [HttpGet]
        [Route("DireccionesParaPedidos/Eliminar")]
        public IActionResult Eliminar(int id)
        {
            CoordinadorDeDireccionesParaPedidos elCoordinador = new CoordinadorDeDireccionesParaPedidos();
            var laDireccionEncontrada = elCoordinador.ObtenerDireccionPorId(id); //el coordinador obtiene la direccion a eliminar por id 


            return View(laDireccionEncontrada);// retorna a la vista  la direccion encontrada 
        }

        [HttpPost]
        [Route("DireccionesParaPedidos/Eliminar")]
        public IActionResult Eliminar(Modelo.DireccionPedido laDireccion)
        {
            try
            {
                CoordinadorDeDireccionesParaPedidos elCoordinador = new CoordinadorDeDireccionesParaPedidos(); //se crea una instancia del  coordinador de direcciones para pedidos

                if (elCoordinador.SiExiste(laDireccion)) //se valida que exista la direccion 
                {
                    elCoordinador.Eliminar(laDireccion);//el coordinador procede a eliminar la direccion 
                    Alert( $"La dirección #{laDireccion.Id} ha sido eliminada.", NotificationType.success); //se muestra el mensaje de exito
                }
                else //si no existe
                {
                    Alert($"La dirección que intenta eliminar no existe", NotificationType.warning); //se advierte que el usuario no exite
                }
               
                   

                    return RedirectToAction("Mostrar");

               

            }
            catch
            {
                Alert($"No es posible eliminar esa dirección", NotificationType.error);

                return  RedirectToAction("Mostrar");
               
            }

        }

       
    }
}

AsopaabiOnline.UI/Views/DireccionesParaPedidos/Agregar.cshtml
@model AsopaabiOnline.Modelo.DireccionPedido

@{
    ViewBag.Title = "Agregar dirección";

}

<div class="row justify-content-md-center">
    <div class="card w-50">
        <h3 class="card-header  text-center">@ViewBag.Title </h3>

        <div class="card-body">

            <form asp-controller="DireccionesParaPedidos" id="myFom" asp-action="Agregar" method="post">

                <div class="form-group">
                    <label asp-for="IdProvincia" class="control-label"></label>
                    <select id="provincias" asp-for="IdProvincia" asp-items=@(new SelectList(Model.LaListaDeProvincias,"Id","Nombre")) class="form-control" required>
                        <option selected="selected" disabled value="">Seleccione una opción</option>
                    </select>


                </div>

                <div class="form-group">
                    <label asp-for="IdCanton" class="control-label"></label>
                    <select id="cantones" asp-for="IdCanton" class="form-control" required></select>

                </div>

                <div class="form-group">
                    <label asp-for="IdDistrito" class="control-label"></label>
                    <select id="distritos" asp-for="IdDistrito" class="form-control" required></select>


                </div>
                <div class="form-group">
                    <label asp-for="Detalles" class="control-label"></label>
                    <textarea asp-for="Detalles" class="form-control" required></textarea>
                    <span asp-validation-for="Detalles" class="text-danger"></span>
                </div>

                <div class="form-group">
                    <input type="submit" value="Guardar" class="btn btn-success btn-lg btn-block" />
                    <a class="btn btn-secondary btn-lg btn-block" asp-action="Mostrar">Volver</a>
                </div>

            </form>
        </div>
    </div>
</div>



@section Scripts{
    <script type="text/javascript">



        $(document).ready(function () {

            $("#provincias").change(function () {
                $("#cantones").empty();


                $.ajax({
                    type: 'GET',
                    url: '@Url.Action("CargarCantones")',

                    dataType: 'json',

                    data: { id: $("#provincias").val() },

                    success: function (direcciones) {

                        $("#cantones").append('<option value="' + -1 + '">' + "Seleccione una opción" +'</option>');

                        $.each(direcciones, function (recorrer, cantones) {
                            $("#cantones").append('<option value="' + cantones.value + '">' + cantones.text + '</option>');
                        });



                    }


                });
                return false;
            })



             $("#cantones").change(function () {
                $("#distritos").empty();

                $.ajax({
                    type: 'GET',
                    url: '@Url.Action("CargarDistritos")',

                    dataType: 'json',

                    data: { id: $("#cantones").val() },


                    success: function (direcciones) {
                        $("#distritos").append('<option value="' + -1 + '">' + "Seleccione una opción" +'</option>');

                        $.each(direcciones, function (recorrer, cantones) {
                            $("#distritos").append('<option value="' + cantones.value + '">' + cantones.text + '</option>');
                        });
                    }

                });
                return false;
            })



        })


    </script>
}
           

AsopaabiOnline.UI/Views/DireccionesParaPedidos/Eliminar.cshtml
@model AsopaabiOnline.Modelo.DireccionPedido


@{
    ViewBag.Title = "Eliminar dirección";
}





<div class="row justify-content-md-center">
   

    <div class=" card  w-75">

        <div class="card-header">
            <h3 class="card-title "> @ViewBag.Title</h3>

        </div>

        
       
        <div class="card-body text-center">

            <br />
            <h4 class="card-subtitle text-center"> ¿Está seguro que desea eliminar esta dirección?</h4>
            <br />
            <br />
            <dl class="row">

                <dt class="col-sm-2">
                    @Html.DisplayNameFor(model => model.Id)
                </dt>
                <dd class="col-sm-10">
                    @Html.DisplayFor(model => model.Id)
                </dd>
                <dt class="col-sm-2">
                    @Html.DisplayNameFor(model => model.IdProvincia)
                </dt>
                <dd class="col-sm-10">
                    @Html.DisplayFor(model => model.IdProvinciaNavigation.Nombre)
                </dd>
                <dt class="col-sm-2">
                    @Html.DisplayNameFor(model => model.IdCanton)
                </dt>
                <dd class="col-sm-10">
                    @Html.DisplayFor(model => model.IdCantonNavigation.Nombre)
                </dd>
                <dt class="col-sm-2">
                    @Html.DisplayNameFor(model => model.IdDistrito)
                </dt>
                <dd class="col-sm-10">
                    @Html.DisplayFor(model => model.IdDistritoNavigation.Nombre)
                </dd>


                <dt class="col-sm-2">
                    @Html.DisplayNameFor(model => model.Detalles)
                </dt>
                <dd class="col-sm-10">
                    @Html.DisplayFor(model => model.Detalles)
                </dd>


            </dl>
        </div>

        <div class="card-footer text-center">


            <button type="button" class="btn btn-danger btn-lg " data-toggle="modal" data-target="#eliminar">Si</button>
            <a class="btn btn-secondary btn-lg  " asp-action="Mostrar">No</a>


            <div class="modal fade" id="eliminar" tabindex="-1" role="dialog" aria-labelledby="exampleModalCenterTitle" aria-hidden="true">
                <div class="modal-dialog modal-dialog-centered" role="document">
                    <div class="modal-content">
                        <div class="modal-header">
                            <h5 class="modal-title" id="exampleModalCenterTitle">Eliminar dirección</h5>
                            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                <span aria-hidden="true">&times;</span>
                            </button>
                        </div>
                        <div class="modal-body">
                            La dirección #@Model.Id se va a eliminar, ¿estas deacuerdo?
                        </div>
                        <div class="modal-footer">
                            <button type="button" class="btn btn-secondary" data-dismiss="modal">Cancelar</button>
                            <form asp-action="Eliminar">
                                <input type="hidden" asp-for="Id" />
                                <button type="submit" class="btn btn-primary">Eliminar</button>

                            </form>
                        </div>
                    </div>
                </div>
            </div>




        </div>

    </div>
   </div>

AsopaabiOnline.UI/Views/DireccionesParaPedidos/Mostrar.cshtml
@model IEnumerable<AsopaabiOnline.Modelo.DireccionPedido>

@{
    ViewBag.Title = "Direcciones";
}






@if (Model.Any())
{

    <div class="card">

        <div class="card-header text-center">
            <h3>@ViewBag.Title</h3>
        </div>
        <div class="m-5">


            <br />
            <div class="m-3">
                <a class="btn" asp-controller="DireccionesParaPedidos" asp-action="Agregar" style="border-radius:25px; background-color:#96c401"
                   data-toggle="tooltip" data-placement="top" title="Agregar"><i class="fas fa-plus text-white"></i>  </a>
            </div>

            <br />

            <table class="table table-striped">
                <thead>
                    <tr>
                        <th>
                            @Html.DisplayNameFor(model => model.Id)
                        </th>
                        <th>
                            @Html.DisplayNameFor(model => model.IdProvincia)
                        </th>
                        <th>
                            @Html.DisplayNameFor(model => model.IdCanton)
                        </th>
                        <th>
                            @Html.DisplayNameFor(model => model.IdDistrito)
                        </th>
                        <th>
                            @Html.DisplayNameFor(model => model.Detalles)
                        </th>
                        <th>
                            <label>Opciones</label>
                        </th>

                        <th></th>
                    </tr>
                </thead>
                <tbody>
                    @foreach (var item in Model)
                    {
                        <tr>
                            <td>
                                @Html.DisplayFor(modelItem => item.Id)
                            </td>
                            <td>

                                @Html.DisplayFor(modelItem => item.IdProvinciaNavigation.Nombre)


                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.IdCantonNavigation.Nombre)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.IdDistritoNavigation.Nombre)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.Detalles)
                            </td>


                            <td>


                                <a asp-action="Eliminar" asp-route-id="@item.Id" class="btn btn-lg"
                                   data-toggle="tooltip" data-placement="top" title="Eliminar"> <i class="fas fa-trash text-danger"></i></a>


                            </td>
                        </tr>
                    }

                </tbody>


            </table>
        </div>
    </div>
}
else
{

    <div class="card text-center m-5">
        <div class="card-body">
            <h3>No hay direcciones agregadas</h3>
            <a asp-action="Agregar" asp-controller="DireccionesParaPedidos" class="btn btn-success btn-lg" data-toggle="tooltip" data-placement="top" title="Agregar dirección">
            <i class="fas fa-plus-circle"></i></a>
        </div>
    </div>

}