AsopaabiOnline.UI/Controllers/PedidosController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using AsopaabiOnline.LogicaDeNegocio;
using Microsoft.AspNetCore.Identity;
using AsopaabiOnline.UI.Models;
using AsopaabiOnline.UI.Models.Enums;

namespace AsopaabiOnline.UI.Controllers
{
    //controlador de Pedidos
    public class PedidosController : BaseController //hereda el controlador base para la notificacion de mensajes.
    {
        //Método para mostrar la lista de pedidos

        [HttpGet]
        [Route("Pedidos/Mostrar")]
        public IActionResult Mostrar()
        {
            CoordinadorDePedidos elCoordinador = new CoordinadorDePedidos();
            return View(elCoordinador.ListarPedidos()); //el coordinador de pedidos lista los pedidos encontrados 
        }


        //Método GET y SET para actualizar un pedido

        [HttpGet]
        [Route("Pedidos/Actualizar")]
        public IActionResult Actualizar(int id)
        {
            CoordinadorDePedidos elCoordinador = new CoordinadorDePedidos();
            var elPedidoEncontrado = elCoordinador.ObtenerPedidoPorId(id); //el coordinador busca el pedido por Id y se lo pasa a la vista 

            return View(elPedidoEncontrado);
        }
        [HttpPost]
        [Route("Pedidos/Actualizar")]
        public IActionResult Actualizar(Modelo.Pedido elPedido)
        {
            try
            {
                
                CoordinadorDePedidos elCoordinador = new CoordinadorDePedidos();
                
                if (elCoordinador.siExite(elPedido)) //el coordinador verifica la existencia antes de actualizar
                {
                    elCoordinador.Actualizar(elPedido); //el coordinador procede a actualizar el pedido
                    Alert("Pedido actualizado.", NotificationType.success);
                }
                else
                {
                    Alert("Parece que este pedido NO existe.", NotificationType.warning);
                }
                return View();
            }
            catch
            {
                Alert("No es posible actualizar este pedido. ¡Inténtalo de nuevo!", NotificationType.error);
                return RedirectToAction("Mostrar");
            }
        }


        //Permite mostrar la pantalla para cambiar el estado del pedido
        [HttpGet]
        [Route("Pedidos/CambiarEstadoDePedido")]
        public IActionResult CambiarEstadoDePedido(int id)
        {
            CoordinadorDePedidos elCoordinador = new CoordinadorDePedidos();
            var elPedidoEncontrado = elCoordinador.ObtenerPedidoPorId(id); 
            ViewBag.IdDelPedido = elPedidoEncontrado.Id;
            return View();
        }

        //Método GET y POST que permite cambiar el estado del pedido a en proceso 
        [HttpGet]
        [Route("Pedidos/CambiarAPedidoEnProceso")]
        public IActionResult CambiarAPedidoEnProceso(int id)
        {

            CoordinadorDePedidos elCoordinador = new CoordinadorDePedidos();
            var elPedidoEncontrado = elCoordinador.ObtenerPedidoPorId(id); //se obtiene el pedido por el id

            return View(elPedidoEncontrado);
        }
        [HttpPost]
        [Route("Pedidos/CambiarAPedidoEnProceso")]
        public IActionResult CambiarAPedidoEnProceso(Modelo.Pedido elPedido)
        {
            try
            {
                CoordinadorDePedidos elCoordinador = new CoordinadorDePedidos();
                if (elCoordinador.SiEstadoEsEnProceso(elPedido)) //si ya esta en estado en proceso le muestra un mensaje de advertencia
                {
                    Alert("Parece que este pedido ya está en proceso.", NotificationType.warning);
                }
                else if (elCoordinador.SiEstadoEsFinalizado(elPedido)) //si esta en estado finalizado le muestra un mensaje de advertencia
                {
                    Alert("No se puede cambiar porque este pedido ya esta finalizado.", NotificationType.warning);
                    return RedirectToAction("Mostrar");
                }
                    
                else 
                {
                    elCoordinador.CambiarAPedidoEnProceso(elPedido);
                    Alert("Pedido actualizado ha estado en proceso", NotificationType.success);
                }
               

                return RedirectToAction("PedidosEnProceso");
            }
            catch
            {
                Alert("Algo ha salido mal, inténtalo de nuevo!", NotificationType.error);
                return RedirectToAction("Mostrar");
            }
        }



        //Método GET y POST que permite cambiar el estado del pedido a finalizado
        [HttpGet]
        [Route("Pedidos/CambiarAPedidoFinalizado")]
        public IActionResult CambiarAPedidoFinalizado(int id)
        {
            CoordinadorDePedidos elCoordinador = new CoordinadorDePedidos();
            var elPedidoEncontrado = elCoordinador.ObtenerPedidoPorId(id);//el coordinador obtiene un pedido por id

            return View(elPedidoEncontrado);
        }
        [HttpPost]
        [Route("Pedidos/CambiarAPedidoFinalizado")]
        public IActionResult CambiarAPedidoFinalizado(Modelo.Pedido elPedido)
        {
            try
            {
                CoordinadorDePedidos elCoordinador = new CoordinadorDePedidos();
                if (elCoordinador.SiEstadoEsFinalizado(elPedido)) //si ya esta en estado finalizado le muestra un mensaje de advertencia
                {
                    Alert("Parece que este pedido ya esta finalizado.", NotificationType.warning);
                }
                else if (elCoordinador.SiEstadoEsReciente(elPedido)) //si esta en estado reciente le muestra un mensaje de advertencia
                {
                    Alert("Primero se debe cambiar a estado en proceso para que el cliente le dé seguimiento", NotificationType.warning);
                    return RedirectToAction("Mostrar");
                }
                else
                {
                    elCoordinador.CambiarAPedidoFinalizado(elPedido);
                    Alert("Pedido actualizado ha estado finalizado", NotificationType.success);
                }


                return RedirectToAction("PedidosFinalizados");
            }
            catch
            {
                Alert("Algo ha salido mal, inténtalo de nuevo!", NotificationType.error);
                return RedirectToAction("Mostrar");
            }
        }







        //Método para ver la lista de pedidos recientes

        [HttpGet]
        [Route("Pedidos/PedidosRecientes")]
        public IActionResult PedidosRecientes()
        {
            CoordinadorDePedidos elCoordinador = new CoordinadorDePedidos();
            return View(elCoordinador.ListarPedidosRecientes());
        }
        //Método para ver la lista de pedidos en proceso

        [HttpGet]
        [Route("Pedidos/PedidosEnProceso")]
        public IActionResult PedidosEnProceso()
        {
            CoordinadorDePedidos elCoordinador = new CoordinadorDePedidos();
            return View(elCoordinador.ListarPedidosEnProceso());
        }

        //Método para ver la lista de pedidos finalizados
        [HttpGet]
        [Route("Pedidos/PedidosFinalizados")]
        public IActionResult PedidosFinalizados()
        {
            CoordinadorDePedidos elCoordinador = new CoordinadorDePedidos();
            return View(elCoordinador.ListarPedidosFinalizados());
        }

    }
}

AsopaabiOnline.UI/Controllers/ProductosController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using AsopaabiOnline.LogicaDeNegocio;
using Microsoft.AspNetCore.Hosting;
using System.IO;
using AsopaabiOnline.Modelo;
using AsopaabiOnline.UI.Models.Enums;

namespace AsopaabiOnline.UI.Controllers
{
    //controlador de productos
    public class ProductosController : BaseController //hereda el controlador base para la notificacion de mensajes.
    {
       private readonly IWebHostEnvironment hostEnvironment;


        public ProductosController(IWebHostEnvironment environment )
        {
            this.hostEnvironment = environment;
        }


        //Método GET y  POST para agregar productos
        [HttpGet]
        [Route("Productos/Agregar")]
        public IActionResult Agregar()
        {
            return View();
        }

        [HttpPost]
        [Route("Productos/Agregar")]
        public IActionResult Agregar(Modelo.Producto elProducto)
        {
            try
            {
                CoordinadorDeProductos elCoordinador = new CoordinadorDeProductos();  // se crea un objeto coordinador.
                if ( !elCoordinador.SiExiste(elProducto) || elProducto != null) //si no existe el producto 
                {
                    if (elCoordinador.SiExiteCodigo(elProducto)) //se valida la existencia de el codigo a ingresar para que no sea el mismo 
                    {
                        Alert("Parece que ya existe un producto con ese código,Inténtalo de nuevo agregando otro código diferente! ", NotificationType.warning);
                        return View(elProducto);
                    }
                    elProducto.Imagen = SubirImagen(elProducto); // se carga la imagen al codigo y se le asigna el nombre de la imagen del producto que se va a guardar
                    elCoordinador.Agregar(elProducto); // se agregan los productos a la tabla PRODUCTO de la base de datos 
                    Alert("Producto guardado.", NotificationType.success);



                }
                else
                {
                    Alert("Parece que este producto ya existe. Inténtalo de nuevo agregando otro!", NotificationType.warning);

                }

                return RedirectToAction("Mostrar");

            }
            catch
            {
                Alert("Se deben completar los campos para agregar el producto.", NotificationType.error);

                return View();
            }
        }
         


        //Se utiliza para eliminar la ruta de una imagen
        public void EliminarRutaDeImagen(Producto producto) 
        {
            try
            {
                CoordinadorDeProductos elCoordinador = new CoordinadorDeProductos();
                var elProductoEncontrado = elCoordinador.ObtenerProductoPorId(producto.Id); //se obtiene el producto
                string nombreDelaImagen = elProductoEncontrado.Imagen; //se obtiene el nombre de la imagen 
                string folder = Path.Combine(hostEnvironment.WebRootPath, "imagenes");  // se obtiene el folder de imagenes donde guardan

                string filePath = Path.Combine(folder, nombreDelaImagen); //creamos la ruta de una imagen en especifico 
                if (System.IO.File.Exists(filePath))  //si la ruta existe entonces se procede a eliminar
                {
                    System.IO.File.Delete(filePath); //se elimina esa ruta de la carpeta 
                }
            }
            catch
            {

            }
        }

        //Método para subir una imagen en una carpeta del codigo

        public string SubirImagen(Modelo.Producto elProducto)
        {

            string uniqueFileName = null;

            if (elProducto.ImageFile != null)
            {
                string uploadsFolder = Path.Combine(hostEnvironment.WebRootPath, "imagenes"); //obtenemos  el folder donde se va a guardar la imagen 
                uniqueFileName = Guid.NewGuid().ToString() + "_" + elProducto.ImageFile.FileName; //generamos un nombre unico para la imagen 
                string filePath = Path.Combine(uploadsFolder, uniqueFileName); //generamos la ruta de la imagen 
                using (var fileStream = new FileStream(filePath, FileMode.Create)) 
                {
                    elProducto.ImageFile.CopyTo(fileStream); //se copia el archivo de la imagen la carpeta
                }
            }
            return uniqueFileName;
        }



        //Método para mostrar la lista de productos
        [HttpGet]
        [Route("Productos/Mostrar")]
        public IActionResult Mostrar()
        {
            CoordinadorDeProductos elCoordinador = new CoordinadorDeProductos();

           
            return View(elCoordinador.ListarProductos());
        }


        //Método GET y SET para actualizar un producto
    [HttpGet]
    [Route("Productos/Actualizar")]
    public IActionResult Actualizar(int id)
      {
            CoordinadorDeProductos elCoordinador = new CoordinadorDeProductos();
            var elProductoEncontrado = elCoordinador.ObtenerProductoPorId(id);

            return View(elProductoEncontrado);
        }
    
    [HttpPost]
    [Route("Productos/Actualizar")]
    public IActionResult Actualizar(Modelo.Producto elProducto)
    {
          
           
            try
            {
                CoordinadorDeProductos elCoordinador = new CoordinadorDeProductos();
                if (elCoordinador.SiExiste(elProducto) )
                {

                    if (elProducto.ImageFile != null) //si se carga el archivo de la imagen 
                    {
                        elProducto.Imagen = SubirImagen(elProducto); //se sube la imagen al folder del codigo y se le asigna la direccion al atributo imagen para ser actualizado en la tabla 
                    }

                    elCoordinador.Actualizar(elProducto); // actualiza el producto deseado a la tabla de PRODUCTO
                    Alert("Producto actualizado.", NotificationType.success);
                }
                else
                {
                    Alert("Parece que este producto NO existe.", NotificationType.warning);
                }
               
              

               
            return View(elProducto);
        }
        catch 
        {
                Alert("No es posible actualizar este producto. ¡Inténtalo de nuevo!", NotificationType.error);
                return RedirectToAction("Mostrar");
            }

        
      
    }



        //Método GET y SET para eliminar un producto
        [HttpGet]
        [Route("Productos/Eliminar")]
        public IActionResult Eliminar(int id)
        {
            CoordinadorDeProductos elCoordinador = new CoordinadorDeProductos();
            var elProductoEncontrado = elCoordinador.ObtenerProductoPorId(id); //Se busca el producto a eliminar 

            return View(elProductoEncontrado);
        }



        [HttpPost]
        [Route("Productos/Eliminar")]
        public IActionResult Eliminar(Modelo.Producto elProducto)
        {
            try
            {
                CoordinadorDeProductos elCoordinador = new CoordinadorDeProductos();
                if (elCoordinador.SiExiste(elProducto))//si existe el producto 
                {
                    EliminarRutaDeImagen(elProducto); //se elimina la imagen del folder ´wwwroot/imagenes´  local 
                    elCoordinador.Eliminar(elProducto); //se elimina el producto deseado de la tabla PRODUCTO
                    Alert("Producto eliminado.", NotificationType.success);

                }
                else
                {
                    Alert("El producto que intentas eliminar, NO existe!", NotificationType.warning);
                }
               
              
                return RedirectToAction("Mostrar");

            }
            catch
            {
                Alert("No es posible eliminar este producto. ¡Inténtalo de nuevo!", NotificationType.error);
                return View();
            }



        }


        



    }

}

AsopaabiOnline.UI/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - AsopaabiOnline</title>

    @* Vendor CSS Files*@
    <link href="assets/vendor/bootstrap/css/bootstrap.min.css" rel="stylesheet">
    <link href="assets/vendor/icofont/icofont.min.css" rel="stylesheet">
    <link href="assets/vendor/boxicons/css/boxicons.min.css" rel="stylesheet">
    <link href="assets/vendor/remixicon/remixicon.css" rel="stylesheet">
    <link href="assets/vendor/venobox/venobox.css" rel="stylesheet">
    <link href="assets/vendor/owl.carousel/assets/owl.carousel.min.css" rel="stylesheet">
    <link href="assets/vendor/aos/aos.css" rel="stylesheet">

    @*Template Main CSS File*@
   

    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.2/css/all.min.css" />
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>


    <link rel="shortcut icon" href="/imagenes/Iconos/logo.png" type="image/x-icon">

    <link href="assets/css/style.css" rel="stylesheet">
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />

    <link href="~/sweetAlert/sweetalert.css" rel="stylesheet" />
    <script src="~/sweetAlert/sweetalert.min.js"></script>

</head>
<body style="background-color: #CFD8DC">
    <header>
        @if (User.Identity.IsAuthenticated)
        {
        <nav class="navbar navbar-expand-lg navbar-light bg-light box-shadow mb-3">




            <a class="navbar-brand" asp-action="Tienda" asp-controller="Home" data-toggle="tooltip" data-placement="top" title="Tienda Asopaabi Online">

                <img src="~/imagenes/Iconos/logo.png" width="40" height="40" class="d-inline-block align-top" alt="">
                Asopaabi Online
            </a>

           
            <div class="container">
                <div>

                    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                            aria-expanded="false" aria-label="Toggle navigation">
                        <span class="navbar-toggler-icon"></span>
                    </button>
                </div>




                @if (User.Identity.IsAuthenticated)
                {
                    <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                        <div style="margin-left:30px !important;">
                            <partial name="_LoginPartial" />

                        </div>



                        <ul class="navbar-nav ">

                            @if (User.IsInRole("Deshabilitado"))
                            {
                                <li class="nav-item">
                                    <a class="nav-link " asp-controller="Cuenta" asp-action="DisableView">
                                        <i class="fas fa-users-slash"></i> Cuenta deshabilitada
                                    </a>
                                </li>
                            }



                            @if (User.IsInRole("Administrador") || User.IsInRole("AsistenteAdministrativo"))
                            {


                                <li class="nav-item dropdown">
                                    <a class="nav-link text-dark dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false"
                                       data-placement="top" title="Configuraciones administrativas">
                                        <i class="fas fa-cogs"></i> Configuración
                                    </a>
                                    <div class="dropdown-menu" aria-labelledby="navbarDropdown">

                                        <a class="dropdown-item" asp-controller="Productos" asp-action="Mostrar">
                                            <i class="fas fa-leaf"></i> Productos
                                        </a>
                                        <a class="dropdown-item" asp-controller="Pedidos" asp-action="Mostrar">
                                            <i class="fas fa-cart-arrow-down"></i> Pedidos
                                        </a>

                                        @if (User.IsInRole("Administrador"))
                                        {

                                            <div class="dropdown-divider"></div>


                                            <a class="dropdown-item" asp-controller="Administrador" asp-action="RolesList"><i class="fas fa-user-tag"></i> Roles </a>
                                            <button class="btn  dropdown-toggle" type="button" aria-labelledby="navbarDropdown" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false"><i class="fas fa-user-cog"></i> Usuarios</button>
                                            <div class="dropdown-menu">
                                                <a class=" dropdown-item" asp-controller="Administrador" asp-action="UserList"><i class="fas fa-users"></i>  Usuarios</a>
                                                <a class="dropdown-item" asp-controller="Administrador" asp-action="DisableUsersList"><i class="fas fa-users-slash"></i>Deshabilitados</a>
                                                <a class="dropdown-item" asp-controller="Administrador" asp-action="CustomerList"><i class="far fa-address-book"></i> Clientes </a>
                                                <a class="dropdown-item" asp-controller="Administrador" asp-action="EmployeeList"><i class="fas fa-user-tie"></i> Empleados</a>

                                            </div>

                                        }

                                    </div>
                                </li>

                            }


                            @if (User.IsInRole("Cliente") || User.IsInRole("Administrador") || User.IsInRole("AsistenteAdministrativo"))
                            {
                                <li class="nav-item">
                                    <a class="nav-link text-dark" asp-controller="CarritoDeCompras" asp-action="CarritoDeCompras"
                                       data-toggle="tooltip" data-placement="top" title="Carrito de compras">
                                        <i class="fas fa-shopping-cart "></i> Carrito
                                    </a>
                                </li>

                                <li class="nav-item">
                                    <a class="nav-link text-dark" asp-action="Mostrar" asp-controller="HistorialPedidos"
                                       data-toggle="tooltip" data-placement="top" title="Historial de pedidos">
                                        <i class="fas fa-history"></i> Historial
                                    </a>

                                </li>
                            }
                        </ul>
                    </div>
                }




            </div>

        </nav>

        }
    </header>

    <div class="container-fluid">
        <main role="main" class="pb-3">
            @Html.Partial("_NotificationPanel")
            @RenderBody()

        </main>
    </div>
    <br />
    @if (User.Identity.IsAuthenticated)
    {
        <footer class="border-top footer text-muted" style="  background-color: #f8f9fa;">

            <div class="container ">
                <span>
                    &copy; 2020 -Asopaabi Online
                    @if (User.Identity.IsAuthenticated)
                    {
                        <a style="padding-left:70%;"> Hola @User.Identity.Name!</a>
                    }
                </span>

                
            </div>



        </footer>

    }
    

        <script src="~/lib/jquery/dist/jquery.min.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
        @RenderSection("Scripts", required: false)
    </body>
</html>

AsopaabiOnline.UI/Views/Shared/_NotificationPanel.cshtml
@if (TempData["notification"] != null)
{
    @Html.Raw(TempData["notification"])
}

AsopaabiOnline.UI/Views/Shared/_PedidoPartial.cshtml
@model AsopaabiOnline.Modelo.Pedido



<h4 class="text-center"> Detalles del pedido </h4>
<hr />
<br />
<div class="row">
    


    <div class="col-4">
        @if (Model.ListaDeDirecciones.Count > 0)
        {
            <label asp-for="IdDireccion" class="control-label"></label>
            <select asp-for="IdDireccion" asp-items=@(new SelectList(Model.ListaDeDirecciones,"Id","Detalles")) class="form-control" required>
                <option selected="selected" disabled value="">Seleccione una opción</option>
            </select>
            <span asp-validation-for="IdDireccion" class="text-danger"></span>
        }
        else {
        
        <label class="text-center">No hay direcciones</label><br />
        <a asp-action="Agregar" asp-controller="DireccionesParaPedidos" class="btn btn-primary active" role="button" data-bs-toggle="button" aria-pressed="true">Agregar una direccion</a>

        }

    </div>


    <div class="col-4">
        <label class="control-label">Detalles adicionales</label>
        <textarea asp-for="Notas" class="form-control" required></textarea>
        <span asp-validation-for="Notas" class="text-danger"></span>
    </div>

    <div class="col-4">
        <label asp-for="TipoPago" class="control-label"></label>
        <select asp-for="TipoPago" asp-items="Html.GetEnumSelectList<AsopaabiOnline.Modelo.OpcionesDePago>()" class="form-control" required>
            <option selected="selected" disabled value="">Seleccione una opción</option>
        </select>
        <span asp-validation-for="TipoPago" class="text-danger"></span>

    </div>


    <hr />

    <br />

</div>
   

       
  

   