AsopaabiOnline.UI/Controllers/DireccionPedidosController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using AsopaabiOnline.LogicaDeNegocio;

namespace AsopaabiOnline.UI.Controllers
{
    public class DireccionPedidosController : Controller
    {
        [HttpGet]
        [Route("DireccionPedidos/Agregar")]
        public IActionResult Agregar()
        {

            Modelo.DireccionPedido laDireccionDelPedido = new Modelo.DireccionPedido();
            //CoordinadorDeDistritos elCoordinadorDeDistritos = new CoordinadorDeDistritos();
            //CoordinadorDeCantones elCoordinadorDeCantones = new CoordinadorDeCantones();
            CoordinadorDeProvincias elCoordinadorDeProvincias = new CoordinadorDeProvincias();


            laDireccionDelPedido.LaListaDeProvincias = elCoordinadorDeProvincias.ListarProvincias();
            if (ViewBag.SeleccionDeProvincia != null)
            {
                ViewBag.mensaje = "Debe seleccionar uno ";
            }
            //    laDireccionDelPedido.LaListaDeCantones = elCoordinadorDeCantones.ListarCantonesPorIdDeProvincia(laDireccionDelPedido.IdProvincia);
            //laDireccionDelPedido.LaListaDeDistritos = elCoordinadorDeDistritos.ListarDistritosPorIdDeCanton(laDireccionDelPedido.IdDistrito);
            return View(laDireccionDelPedido);
        }

        [Route("DireccionPedidos/Agregar")]
        public IActionResult Agregar(Modelo.DireccionPedido laDireccion)
        {
            try
            { 
                CoordinadorDeDireccionesDeLosPedidos elCoordinador = new CoordinadorDeDireccionesDeLosPedidos();

                elCoordinador.Agregar(laDireccion);
                return RedirectToAction("Mostrar");
            }
            catch
            {
                return View();
            }


        }


    }
}

AsopaabiOnline.UI/Views/DireccionPedidos/Agregar.cshtml
@model AsopaabiOnline.Modelo.DireccionPedido

@{
    ViewBag.Title = "AgregarDireccion";

}
<h3>Dirección de los pedidos</h3>
<hr />

<div class="row">
    <div class="col-md-4">
    
        <form asp-controller="DireccionPedidos" asp-action="Agregar" method="post">

            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
          


            <table>
                <thead>
                    <tr>
                        <th>
                            <label asp-for="IdProvincia" class="control-label"></label>
                        </th>
                        <th>
                            <label asp-for="IdCanton" class="control-label"></label>
                        </th>
                        <th>
                            <label asp-for="IdDistrito" class="control-label"></label>
                        </th>
                        <th>
                            <label asp-for="Detalles" class="control-label"></label>
                        </th>
                    </tr>
                </thead>
                <tbody>
                    <tr>
                        <td>
                            <select id="SeleccionDeProvincia" asp-for="IdProvincia" asp-items=@(new SelectList(Model.LaListaDeProvincias,"Id","Nombre")) class="form-control" style="width:230px;">
                                <option selected="selected" disabled value="">Seleccione una opción</option>
                            </select>

                            <span asp-validation-for="IdProvincia" class="text-danger"></span>
                            <div ><a @ViewBag.mensaje></a>  </div>
                        </td>
                        <td>
                            @*<select asp-for="IdCanton" asp-items="new SelectList(Model.LaListaDeCantones)" class="form-control">
                                <option selected="selected" disabled value="">Seleccione una opción</option>
                            </select>
                            <span asp-validation-for="IdCanton" class="text-danger"></span>*@
                        </td>
                        <td>
                            @*<select asp-for="IdDistrito" asp-items="new SelectList(Model.LaListaDeDistritos)" class="form-control">
                                <option selected="selected" disabled value="">Seleccione una opción</option>
                            </select>
                            <span asp-validation-for="IdDistrito" class="text-danger"></span>*@
                        </td>

                        <td>
                            <input asp-for="Detalles" class="form-control" />
                            <span asp-validation-for="Detalles" class="text-danger"></span>
                        </td>

                    </tr>
                </tbody>
            </table>
            <hr />
            <br />
            <div class="form-group">
                <input type="submit" value="Guardar" class="btn btn-outline-success" />

            </div>

        </form>
</div>
 </div>